# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk16

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
# Отправлять уведомление на почту lester_g@inbox.ru если сборка упала
notifications:
  email:
    recipients:
     - lester_g@inbox.ru
    on_success: never # default: change
    on_failure: always # default: always
env:
  global:
    CODECOV_TOKEN="82b3f62e-56c6-4f9d-bd97-e88f0f1552b0"
